# Generated by Django 6.0 on 2025-12-19 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('duracao_minutos', models.IntegerField(verbose_name='Duração (min)')),
                ('classificacao', models.CharField(choices=[('L', 'Livre'), ('10', '10 anos'), ('12', '12 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], max_length=10, verbose_name='Classificação Indicativa')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=50, verbose_name='Sala de Exibição')),
                ('horario', models.DateTimeField(verbose_name='Horário da Sessão')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço do Ingresso')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilheteria.filme', verbose_name='Filme')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
            },
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('PIX', 'PIX')], max_length=50, verbose_name='Forma de Pagamento')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilheteria.sessao', verbose_name='Sessão')),
            ],
        ),
    ]
