# Generated by Django 6.0 on 2025-12-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilheteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='tipo',
            field=models.CharField(choices=[('INTEIRA', 'Inteira'), ('MEIA', 'Meia'), ('ESTUDANTE', 'Estudante (Gratuito)'), ('CORTESIA', 'Cortesia (Gratuito)')], default='INTEIRA', max_length=20, verbose_name='Tipo de Ingresso'),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor Pago'),
        ),
    ]
