# Generated by Django 6.0 on 2025-12-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilheteria', '0002_ingresso_tipo_ingresso_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='tipo',
            field=models.CharField(choices=[('INTEIRA', 'Inteira'), ('MEIA', 'Meia')], default='INTEIRA', max_length=20, verbose_name='Tipo de Ingresso'),
        ),
    ]
