# Generated by Django 6.0 on 2025-12-28 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilheteria', '0003_alter_ingresso_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessao',
            name='preco',
        ),
    ]
