# Generated by Django 6.0 on 2025-12-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilheteria', '0004_remove_sessao_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Poster do Filme'),
        ),
    ]
