# Generated by Django 6.0 on 2025-12-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilheteria', '0005_filme_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessao',
            name='sala',
        ),
    ]
